cache_dir: cache/
ckpt_dir: ckpt/
epochs: 150
eval_batch_size: 32
eval_interval: 1
log_dir: ./logs
lr: 0.0003
max_grad_norm: 1.0
metrics:
- ndcg
- recall
num_proc: 1
patience: 20
rand_seed: 2024
reproducibility: true
run_id: genrec_default
steps: null
tensorboard_log_dir: ./logs
topk:
- 5
- 10
train_batch_size: 256
val_metric: ndcg@10
warmup_steps: 10000
weight_decay: 0.0
