activation_function: gelu_new
attn_pdrop: 0.5
chunk_size: 1024
codebook_size: 256
embd_pdrop: 0.5
faiss_omp_num_threads: 32
initializer_range: 0.02
layer_norm_epsilon: 1e-12
log_dir: ./logs
mask_ratio: 0.15
max_item_seq_len: 50
metadata: sentence
n_codebook: 32
n_edges: 50
n_embd: 448
n_head: 4
n_inner: 1024
n_layer: 2
num_beams: 50
num_workers: 64
opq_gpu_id: 0
opq_use_gpu: false
propagation_steps: 3
reconstruction_weight: 0.5
resid_pdrop: 0.0
sent_emb_batch_size: 512
sent_emb_dim: 768
sent_emb_model: sentence-transformers/sentence-t5-base
sent_emb_pca: 128
temperature: 0.07
tensorboard_log_dir: ./logs
